version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/context"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/context"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

